name: Form Submission Handler

on:
  workflow_dispatch:
    inputs:
      formData:
        description: 'Form Data'
        required: true
        type: string
      fileData:
        description: 'File Data'
        required: false
        type: string

jobs:
  save-response:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Save form response
        run: |
          echo "$INPUT_FORMDATA" > responses/response_$(date +'%Y-%m-%dT%H:%M:%S%z').json

      - name: Save uploaded files
        if: ${{ inputs.fileData != '' }}
        run: |
          echo "$INPUT_FILEDATA" > uploads/file_$(date +'%Y-%m-%dT%H:%M:%S%z')

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add responses/* uploads/*
          git commit -m "Save form submission" || true
          git push origin main
